---
version: 2.1

executors:
  ruby_executor:
    working_directory: /mnt/ramdisk
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
  rails_executor:
    working_directory: /mnt/ramdisk
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.8-alpine-postgis
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: vita-min_test
commands:
  install_system_dependencies:
    description: "Install system dependencies"
    steps:
      - run:
          name: install system dependencies
          command: |
            sudo apt-get update && \
            sudo apt-get install -y pdftk ghostscript postgresql-client
  install_js_dependencies:
    description: "Install JS dependencies"
    steps:
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install --frozen-lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - /mnt/ramdisk/node_modules
            - ~/.npm
  install_ruby_dependencies:
    description: "Install Ruby dependencies"
    steps:
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: install bundler & ruby dependencies
          command: |
            gem install bundler:2.2.5 --no-document && \
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: [/mnt/ramdisk/vendor/bundle]
  setup_test_db:
    description: "Setup test database"
    steps:
      - run:
          name: Preparing DB checksum
          command: git log --pretty=format:'%H' -n 1 -- db/ > /tmp/db-checksum
      - restore_cache:
          key: pg-dump-v1-{{ checksum "/tmp/db-checksum" }}
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Preparing databases
          command: |
            if [ -e /tmp/pg_dump.sql ] ; then psql < /tmp/pg_dump.sql ; exit ; fi
            echo "Creating databases"
            bundle exec rake db:schema:load
            pg_dump -d vita-min_test > /tmp/pg_dump.sql
      - save_cache:
          key: pg-dump-v1-{{ checksum "/tmp/db-checksum" }}
          paths: [/tmp/pg_dump.sql]
jobs:
  run_js_tests:
    executor: ruby_executor
    steps:
      - checkout
      - install_js_dependencies
      - run: mkdir ~/test-results && mkdir ~/test-results/rspec && mkdir ~/test-results/jest
      - run:
          command: npm test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test-results/jest/
      - store_test_results:
          path: ~/test-results
  run_ruby_tests:
    executor: rails_executor
    parallelism: 1
    steps:
      - checkout
      - install_js_dependencies
      - install_system_dependencies
      - install_ruby_dependencies
      - setup_test_db
      - run: |
          RAILS_CACHE_CLASSES=1 bundle exec rspec \
              --format RspecJunitFormatter \
              --out ~/test-results/rspec/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: ~/test-results
  deploy_to_aptible--demo:
    executor: ruby_executor
    steps:
      - checkout
      - run: echo $APTIBLE_PUBLIC_KEY >> ~/.ssh/known_hosts
      - run: git fetch --depth=1000000
      - run: git push git@beta.aptible.com:vita-min-demo/vita-min-demo.git $CIRCLE_SHA1:master
    parallelism: 1
  deploy_to_aptible--production:
    executor: ruby_executor
    steps:
      - checkout
      - run: echo $APTIBLE_PUBLIC_KEY >> ~/.ssh/known_hosts
      - run: git fetch --depth=1000000
      - run: git push git@beta.aptible.com:vita-min-prod/vita-min-prod.git $CIRCLE_SHA1:master
    parallelism: 1
workflows:
  version: 2
  ci-and-deploy:
    jobs:
      - run_js_tests
      - run_ruby_tests
      - deploy_to_aptible--demo:
          requires: [run_js_tests, run_ruby_tests]
          filters:
            branches:
              only: main
      - deploy_to_aptible--production:
          requires: [run_js_tests, run_ruby_tests]
          filters:
            branches:
              only: release
